name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v2
      - name: Install python dependencies
        run: |
          apt-get update
          apt-get install --yes libpython3.8
      - name: Setting up python env
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install repo dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Generate README file
        run: python update.py
      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
